"""add_remaining_quantity_to_orders

Revision ID: 91283168432c
Revises: a737859ef435
Create Date: 2026-06-04 21:53:13.396128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91283168432c'
down_revision: Union[str, None] = 'a737859ef435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('remaining_quantity', sa.Numeric(precision=14, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'remaining_quantity')
    # ### end Alembic commands ###
